config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bar_tables
  get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'bar_tables#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bar_table.rb
class BarTable < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bar_tables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bar_tables_controller.rb
class BarTablesController < ApplicationController
  before_action :set_bar_table, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /bar_tables or /bar_tables.json
  def index
    @bar_tables = BarTable.all
  end

  # GET /bar_tables/1 or /bar_tables/1.json
  def show
  end

  def correct_user
    @bar_table = current_user.bar_tables.find_by(id: params[:id])
    redirect_to bar_tables_path, notice: "Not authorized to edit this bar table" if @bar_table.nil?
  end

  # GET /bar_tables/new
  def new
    #@bar_table = BarTable.new
    @bar_table = current_user.bar_tables.build
  end

  # GET /bar_tables/1/edit
  def edit
  end

  # POST /bar_tables or /bar_tables.json
  def create
    #@bar_table = BarTable.new(bar_table_params)
    @bar_table = current_user.bar_tables.build(bar_table_params)
    respond_to do |format|
      if @bar_table.save
        format.html { redirect_to bar_table_url(@bar_table), notice: "Bar table was successfully created." }
        format.json { render :show, status: :created, location: @bar_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bar_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bar_tables/1 or /bar_tables/1.json
  def update
    respond_to do |format|
      if @bar_table.update(bar_table_params)
        format.html { redirect_to bar_table_url(@bar_table), notice: "Bar table was successfully updated." }
        format.json { render :show, status: :ok, location: @bar_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bar_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bar_tables/1 or /bar_tables/1.json
  def destroy
    @bar_table.destroy!

    respond_to do |format|
      format.html { redirect_to bar_tables_url, notice: "Bar table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar_table
      @bar_table = BarTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bar_table_params
      params.require(:bar_table).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_tables_helper.rb
module BarTablesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bar_tables/_bar_table.html.erb
<div id="<%= dom_id bar_table %>">
  <div class="mt-4 p-5 bg-black text-white rounded">
    <h1><%= bar_table.first_name %> <%= bar_table.last_name %></h1>
    <p><%= bar_table.email %> | <%= bar_table.phone %> | <%= bar_table.twitter %></p>
    <%= link_to "Edit this bar table", edit_bar_table_path(@bar_table), class:"btn btn-warning" %>
    <%= link_to "Back to bar tables", bar_tables_path,class:"btn btn-secondary" %><br><br>

    <%= button_to "Destroy this bar table", @bar_table, method: :delete, class:"btn btn-danger" %>
  </div>
</div>

app/views/bar_tables/_form.html.erb
<%= form_with(model: bar_table) do |form| %>
  <% if bar_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bar_table.errors.count, "error") %> prohibited this bar_table from being saved:</h2>

      <ul>
        <% bar_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <br>
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name"%>
    <br>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name , class: "form-control",placeholder: "Last Name"%>
    <br>
  </div>

  <div class="form-group">
    <%= form.text_field :email , class: "form-control",placeholder: "E-Mail"%>
    <br>
  </div>

  <div class="form-group">
    <%= form.text_field :phone , class: "form-control",placeholder: "Phone Number"%>
    <br>
  </div>

  <div class="form-group">
    <%= form.text_field :twitter , class: "form-control",placeholder: "Twitter Handle"%>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id , id: :bar_table_user_id, class: "form-control",value: current_user.id,type: :hidden%>
  </div>

  <div>
    <br>
    <%= form.submit class:"btn btn-success"%>
    <br>
  </div>
<% end %>

app/views/bar_tables/edit.html.erb
<h1>Editing bar table</h1>

<%= render "form", bar_table: @bar_table %>

<br>

<div>
  <%= link_to "Show this bar table", @bar_table,class:"btn btn-warning"%>
  <%= link_to "Back to bar tables", bar_tables_path, class:"btn btn-dark" %>
</div>

app/views/bar_tables/index.html.erb
<% if user_signed_in? %>

<h1>Bar tables</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @bar_tables.each do |bar_table| %>
  <% if bar_table.user == current_user %>
      <tr>
        <td><%= link_to bar_table.first_name+" "+bar_table.last_name , bar_table %></td>
        <td><%= bar_table.email %></td>
        <td><%= bar_table.phone %></td>
        <td><%= bar_table.twitter %></td>
        <td><%= link_to 'Delete', bar_table, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm"%></td>
      </tr>
  <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to "New bar table", new_bar_table_path, class:"btn btn-success"%>

<% else %>
  <%= render "home/index", bar_table: @home %>
<% end %>

app/views/bar_tables/new.html.erb
<h1>New bar table</h1>

<%= render "form", bar_table: @bar_table %>

<br>

<div>
  <%= link_to "Back to bar tables", bar_tables_path,class: "btn btn-warning" %>
</div>

app/views/bar_tables/show.html.erb
<%= render @bar_table %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "My Bar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Bar Table", new_bar_table_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <%else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_index.html.erb
<h1>Hello world</h1>

app/views/home/about.html.erb
<h1>About Us :)</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo demo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<%= render "home/header" %>
<div class="container">
  <br>
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>